import type { ActionEffect } from "./combatLog";

export interface MonsterTemplate {
  name: string;
  weight: number;
  enabled: boolean;
  image: string;
  baseHp: number;
  baseAttack: number;
  baseDefense: number;
  baseSpeed?: number;
  actions: {
    name: string;
    description: string;
    actionType: "attack" | "heal" | "buff" | "debuff";
    power: number;
    weight: number;
    cooldown: number;
    isAoe: boolean;
    canTargetSelf: boolean;
    effects?: ActionEffect;
  }[];
}

export const MONSTER_TEMPLATES = {
  wereraccoon: {
    name: "Szopołak",
    weight: 100,
    enabled: true,
    image: "https://i.imgur.com/ihzBYx8.png",
    baseHp: 83,
    baseAttack: 6,
    baseDefense: 6,
    baseSpeed: 7,
    actions: [
      {
        name: "Drapnięcie",
        description: "Szybki atak pazurami",
        actionType: "attack" as const,
        power: 8,
        weight: 100,
        cooldown: 0,
        isAoe: true,
        canTargetSelf: false,
      },
      {
        name: "Ugryzienie",
        description: "Silne ugryzienie, które leczy Szopołaka za 30% zadanych obrażeń",
        actionType: "attack" as const,
        power: 13,
        weight: 100,
        cooldown: 0,
        isAoe: false,
        canTargetSelf: false,
        effects: { lifesteal: 0.3 },
      },
      {
        name: "Rzut śmieciami",
        description: "Rzuca śmieciami, aby osłabić wrogów",
        actionType: "debuff" as const,
        power: 0,
        weight: 50,
        cooldown: 3,
        isAoe: true,
        canTargetSelf: false,
        effects: { weakness: 3, poison: 6 },
      },
    ],
  },
  fishermanGhost: {
    name: "Duch Wędkarza",
    weight: 80,
    enabled: true,
    image: "https://i.imgur.com/YbMVA5e.png",
    baseHp: 128,
    baseAttack: 14,
    baseDefense: 5,
    baseSpeed: 36,
    actions: [
      {
        name: "Zarzutka",
        description:
          "Wszyscy atakujący zostają trafieni haczykiem i łapią się na zarzutkę.",
        actionType: "attack" as const,
        power: 9,
        weight: 100,
        cooldown: 6,
        isAoe: true,
        canTargetSelf: false,
        effects: { stun: true, weakness: 4, strength: 4 } satisfies ActionEffect,
      },
      {
        name: "Połów",
        description: "Przywołuje ryby, które atakują wszystkich przeciwników.",
        actionType: "attack" as const,
        power: 11,
        weight: 80,
        cooldown: 4,
        isAoe: true,
        canTargetSelf: false,
      },
      {
        name: "Ektoplazma",
        description: "Leczy ducha i zwiększa jego obronę.",
        actionType: "heal" as const,
        power: 18,
        weight: 100,
        cooldown: 10,
        isAoe: false,
        canTargetSelf: true,
        effects: { regen: 5 } satisfies ActionEffect,
      },
    ],
  },
  zombieCat: {
    name: "Zombie Bruno",
    weight: 90,
    enabled: true,
    image: "https://i.imgur.com/KUvDKvi.png",
    baseHp: 54,
    baseAttack: 6,
    baseDefense: 13,
    baseSpeed: 45,
    actions: [
      {
        name: "Pazur Zombie",
        description: "Atak pazurami, który może zatruć cel.",
        actionType: "attack" as const,
        power: 10,
        weight: 100,
        cooldown: 0,
        isAoe: false,
        canTargetSelf: false,
        effects: { poison: 4 } satisfies ActionEffect,
      },
      {
        name: "Kradzież Czasu",
        description: "Uderza wroga, nadaje stun i zabiera trochę życia.",
        actionType: "debuff" as const,
        power: 7,
        weight: 80,
        cooldown: 4,
        isAoe: false,
        canTargetSelf: false,
        effects: { stun: true, lifesteal: 0.4 } satisfies ActionEffect,
      },
      {
        name: "Furia Kota",
        description: "Zwiększa atak Zombie Bruno kosztem jego obrony.",
        actionType: "buff" as const,
        power: 0,
        weight: 100,
        cooldown: 5,
        isAoe: false,
        canTargetSelf: true,
        effects: { strength: 6, shield: -4 } satisfies ActionEffect,
      },
      {
        name: "Zaraźliwy Pazur",
        description: "Atak pazurami, który zatruwa wszystkich wrogów.",
        actionType: "attack" as const,
        power: 8,
        weight: 80,
        cooldown: 6,
        isAoe: true,
        canTargetSelf: false,
        effects: { poison: 3 } satisfies ActionEffect,
      },
    ],
  },
  harpy: {
    name: "Harpia",
    weight: 70,
    enabled: true,
    image: "https://i.imgur.com/kQvkEzI.png",
    baseHp: 51,
    baseAttack: 19,
    baseDefense: 6,
    baseSpeed: 43,
    actions: [
      {
        name: "Niepoprawne korzystanie z mikrofonu",
        description: "Atak dźwiękowy, który ogłusza cel.",
        actionType: "attack" as const,
        power: 9,
        weight: 100,
        cooldown: 0,
        isAoe: false,
        canTargetSelf: false,
        effects: { stun: true } satisfies ActionEffect,
      },
      {
        name: "Podmuch",
        description:
          "Silny podmuch wiatru, który zadaje obrażenia wszystkim przeciwnikom.",
        actionType: "attack" as const,
        power: 11,
        weight: 80,
        cooldown: 4,
        isAoe: true,
        canTargetSelf: false,
      },
    ],
  },
  possessedDoll: {
    name: "Opętana Lalka",
    weight: 60,
    enabled: true,
    image: "https://i.imgur.com/qQObiqd.png",
    baseHp: 80,
    baseAttack: 17,
    baseDefense: 13.5,
    baseSpeed: 60,
    actions: [
      {
        name: "Dźgnięcie",
        description: "Szybki atak nożem.",
        actionType: "attack" as const,
        power: 9,
        weight: 100,
        cooldown: 0,
        isAoe: false,
        canTargetSelf: false,
      },
      {
        name: "Złość",
        description: "Zwiększa swój atak.",
        actionType: "buff" as const,
        power: 0,
        weight: 100,
        cooldown: 2,
        isAoe: false,
        canTargetSelf: true,
        effects: { strength: 3 } satisfies ActionEffect,
      },
    ],
  },
  succubus: {
    name: "Sukkub",
    weight: 40,
    enabled: true,
    image: "https://i.imgur.com/clOhBpu.png",
    baseHp: 148,
    baseAttack: 17,
    baseDefense: 5,
    baseSpeed: 24,
    actions: [
      {
        name: "Uwodzenie",
        description: "Zmniejsza atak i obronę celu.",
        actionType: "buff" as const,
        power: 0,
        weight: 100,
        cooldown: 3,
        isAoe: false,
        canTargetSelf: false,
        effects: { weakness: 2, shield: -2 } satisfies ActionEffect,
      },
      {
        name: "Pocałunek Sukkuba",
        description: "Atak, który leczy Sukkuba za 40% zadanych obrażeń.",
        actionType: "attack" as const,
        power: 16,
        weight: 100,
        cooldown: 0,
        isAoe: false,
        canTargetSelf: false,
        effects: { lifesteal: 0.4 } satisfies ActionEffect,
      },
      {
        name: "Piekielne Selfie",
        description: "Zadaje obrażenia wszystkim przeciwnikom i nakłada efekt burn.",
        actionType: "attack" as const,
        power: 14,
        weight: 80,
        cooldown: 8,
        isAoe: true,
        canTargetSelf: false,
        effects: { burn: 5 } satisfies ActionEffect,
      },
    ],
  },
} as const satisfies Record<string, MonsterTemplate>;

export const PLAYER_ABILITIES = [
  {
    name: "Cios",
    description: "Zwykły atak",
    abilityType: "attack" as const,
    power: 10,
    cooldown: 0,
    canTargetPlayers: false,
    canTargetSelf: false,
    isAoe: false,
    isDefault: true,
  },
  {
    name: "Heavy Blow",
    description: "Silny cios, który zadaje dodatkowe obrażenia",
    abilityType: "attack" as const,
    power: 18,
    cooldown: 3,
    canTargetPlayers: false,
    canTargetSelf: false,
    isAoe: false,
    isDefault: true,
  },
  {
    name: "Bandaż",
    description: "Ulecz się lub sojusznika",
    abilityType: "heal" as const,
    power: 20,
    cooldown: 3,
    canTargetPlayers: true,
    canTargetSelf: true,
    isAoe: false,
    isDefault: true,
  },
  {
    name: "Modlitwa",
    description: "Ulecz wszystkich sojuszników w okolicy",
    abilityType: "heal" as const,
    power: 12,
    cooldown: 5,
    canTargetPlayers: false,
    canTargetSelf: true,
    isAoe: true,
    isDefault: true,
  },
  {
    name: "Tarcza Szmato",
    description: "Zyskaj ochronę i odbij obrażenia",
    abilityType: "buff" as const,
    power: 0,
    cooldown: 4,
    canTargetPlayers: false,
    canTargetSelf: true,
    isAoe: false,
    isDefault: true,
    effects: { shield: 15, thorns: 5 },
  },
  {
    name: "Wzmocnienie",
    description: "Zwiększ swoją i sojuszników obronę",
    abilityType: "buff" as const,
    power: 0,
    cooldown: 6,
    canTargetPlayers: false,
    canTargetSelf: true,
    isAoe: true,
    isDefault: true,
    effects: { shield: 10 },
  },
  {
    name: "Zatruta Strzała",
    description: "Atak, który zatruwa cel",
    abilityType: "attack" as const,
    power: 8,
    cooldown: 2,
    canTargetPlayers: false,
    canTargetSelf: false,
    isAoe: false,
    isDefault: true,
    effects: { poison: 3 },
  },
  {
    name: "Płonąca Pięść",
    description: "Atak, który podpala cel",
    abilityType: "attack" as const,
    power: 12,
    cooldown: 3,
    canTargetPlayers: false,
    canTargetSelf: false,
    isAoe: false,
    isDefault: true,
    effects: { burn: 4 },
  },
  {
    name: "Wampirzy Sztylet",
    description: "Atak, który kradnie życie i leczy cię za 30% zadanych obrażeń",
    abilityType: "attack" as const,
    power: 14,
    cooldown: 4,
    canTargetPlayers: false,
    canTargetSelf: false,
    isAoe: false,
    isDefault: true,
    effects: { lifesteal: 0.3 },
  },
  {
    name: "Osłabienie",
    description: "Obniża atak celu",
    abilityType: "debuff" as const,
    power: 0,
    cooldown: 3,
    canTargetPlayers: false,
    canTargetSelf: false,
    isAoe: false,
    isDefault: true,
    effects: { weakness: 5 },
  },
  {
    name: "Odwaga",
    description: "Zwiększa atak wszystkich sojuszników",
    abilityType: "buff" as const,
    power: 0,
    cooldown: 5,
    canTargetPlayers: false,
    canTargetSelf: true,
    isAoe: true,
    isDefault: true,
    effects: { strength: 6 },
  },
  {
    name: "Berserk",
    description: "Zwiększa twój atak, ale pozwala ci atakować sojuszników!",
    abilityType: "buff" as const,
    power: 0,
    cooldown: 12,
    canTargetPlayers: false,
    canTargetSelf: true,
    isAoe: false,
    isDefault: true,
    effects: { berserk: true, strength: 5 },
  },
] as const;
