name: Check Nix Configuration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    # TODO: Also run on macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - name: Validate devShell
        run: |
          nix develop --command true
